// ngClient/src/app/modules/navigation.routes/components/navigation/navigation.component.ts
import {  Component } from '@angular/core';
import {
  faMountainCity,
  faRightFromBracket,
  faUsers,
  IconDefinition,
} from '@fortawesome/free-solid-svg-icons';

@Component({
  selector: 'app-navigation',
  templateUrl: './navigation.component.html',
  styleUrls: ['./navigation.component.css'],
})
export class NavigationComponent {
  userIcon: IconDefinition = faUsers;
  cityIcon: IconDefinition = faMountainCity;
  logged: IconDefinition = faRightFromBracket;
  unLogged: IconDefinition = faUsers;
  navState: boolean = false;
  
  toggle = (_: MouseEvent, state: boolean)  => {
    this.navState = state;
  }
}

<nav [class]="{ 'nav-open': navState }">
  <open-toggle-btn [onclick]="toggle" initialState="on"></open-toggle-btn>
  <a href="/">
    <h1>technical test</h1>
  </a>
  <menu>
    <a
      routerLink="/"
      routerLinkActive="active"
      [routerLinkActiveOptions]="{
        paths: 'exact',
        matrixParams: 'ignored',
        fragment: 'ignored',
        queryParams: 'ignored'
      }"
    >
      <fa-icon [icon]="userIcon" class="icon"></fa-icon>
      <h2>Tourists</h2>
    </a>
    <a
      routerLink="/city"
      routerLinkActive="active"
      [routerLinkActiveOptions]="{
        paths: 'exact',
        matrixParams: 'ignored',
        fragment: 'ignored',
        queryParams: 'ignored'
      }"
    >
      <fa-icon [icon]="cityIcon" class="icon"></fa-icon>
      <h2>Cities</h2>
    </a>
    <a routerLink="/" class="session-link">
      <!-- Todo: use global state to check if is logged -->
      <fa-icon [icon]="unLogged" class="icon session-icon"></fa-icon>
    </a>
  </menu>
</nav>

// Client/src/partials/Navigation/Navigation.tsx
import { useState } from "react";
import { Link, NavLink } from "react-router-dom";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faUsers,
  faMountainCity,
  faRightToBracket,
} from "@fortawesome/free-solid-svg-icons";
import "./Navigation.css";

export function Navigation() {
  const [menu, toggleMenu] = useState(false);

  return (
    <nav className={menu ? "nav-open" : ""}>
      <button onClick={() => toggleMenu(!menu)}>
        <div />
      </button>
      <Link to={"/"}>
        <h1>Technical Test</h1>
      </Link>
      <menu>
        <NavLink
          to="/travelers"
          className={({ isActive }) => (isActive ? "nav-selected" : "")}
        >
          <FontAwesomeIcon icon={faUsers} className="icon" />
          <h2>Tourists</h2>
        </NavLink>
        <NavLink
          to="/cities"
          className={({ isActive }) => (isActive ? "nav-selected" : "")}
        >
          <FontAwesomeIcon icon={faMountainCity} className="icon" />
          <h2>Citites</h2>
        </NavLink>
        <NavLink to="/login" className={"session-icon icon"}>
          <FontAwesomeIcon icon={faRightToBracket} />
        </NavLink>
      </menu>
    </nav>
  );
}
